name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  notify_init:
    runs-on: ubuntu-latest
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      - name: Discord notification PR
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: >
            :lock_with_ink_pen: [[{{ SHORT_SHA }}](<https://github.com/{{ GITHUB_REPOSITORY }}/commit/{{ SHORT_SHA }}>)] [Starting Tezos Multisig build...](<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}?check_suite_focus=true>)
            ```${{ github.event.head_commit.message }}```

  cli_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Retrieve the cached "node_modules" directory (if present)
        uses: actions/cache@v2
        id: node-cache
        with:
          path: cli/node_modules
          key: cli-node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies (if the cached directory was not found)
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: github.ref == 'refs/heads/main' # Only deploy on merge to main
        with:
          branch: gh-pages
          folder: docs

  smart_contracts_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./smart_contracts        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: actions/setup-python@v2
    - name: "Install SmartPy"
      run: |
        curl https://smartpy.io/releases/20210118-6f466eee56038df8fda8b2f77819b83398346296/cli/install.sh | sh -s -- local-install ~/smartpy-cli
    - name: "Build and Test Smart Contracts"
      run: |
        cd smart_contracts
        ./compile.sh
    

  notify_complete:
    runs-on: ubuntu-latest
    needs:
      - notify_init
      - smart_contracts_build
      - cli_build
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      - name: Discord notification PR
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: >
            :lock_with_ink_pen: [[{{ SHORT_SHA }}](<https://github.com/{{ GITHUB_REPOSITORY }}/commit/{{ SHORT_SHA }}>)] [Tezos Multisig built successfully!](<https://github.com/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }}?check_suite_focus=true>)
            ```${{ github.event.head_commit.message }}```

